paths:
  model_path: ${hydra:runtime.cwd}/models/

game:
  base_board_size: 5
  is_general_state: True 

benchmark:
  num_games: 300
  logging_batch: 50
  wandb_project: "Snake-DQN"
agent:
  name: "cnn agent 5 layers using mean in the last output layer"
  hidden_size: 556
  memory_length: 10000
  gamma: 0.99
  learning_rate: 0.001
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  
train:
  update_target_every: 512
  num_episodes: 20000
  logging_batch: 500
  batch_size: 556
  
  
